# Generated by Django 2.2.7 on 2019-11-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_auto_20191117_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_details',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
